spring:
  datasource:
    username: kzm_vlad
    password: 123root@
    driverClassName: com.mysql.cj.jdbc.Driver
    driverDialect: org.hibernate.dialect.MySQLDialect
    url: jdbc:mysql://localhost:3306/bankauthdb?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
    hikari:
      minimum-idle: 1
      maximum-pool-size: 400

  cloud:
    stream:
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
      bindings:
        kafka:
          binder:
            headers: version, action, EventVersion, EntityVersion
        user-event-input:
          destination: user-event
          contentType: application/json
          consumer:
            headerMode: raw
        card-event-input:
          destination: card-event
          contentType: applicatio/json
          consumer:
            headerMode: raw

server:
  port: 8080

resteasy:
  deployment:
    async_job_service_enabled: true

keycloak:
  appRealm: bank
  idmBrokerAuthUrl: http://localhost:8080/auth
  idmBrokerApp: app-broker
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: 123root@
